SiteAudi/SiteAudi/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SiteAudi.Models;
using SiteAudi.Content;

namespace SiteAudi.Controllers
{
    public class AuthenticationController : Controller
    {
        DataBaseContext dbContext = new DataBaseContext();
        //
        // GET: /Authentication/

        [HttpPost]
        public ActionResult Index()
        {
            var users = dbContext.Users;
            String login = Request.Params["login"];
            String pwd = Request.Params["pwd"];
            if(login!=""&&pwd!="")
            {
                User user1 = users.FirstOrDefault(u => u.Email == login);
                if (user1 == null)
                    return RedirectToAction("Index", "Registration");
                else
                {
                    user1 = users.FirstOrDefault(u => u.Password == pwd);
                    if (user1 == null)
                    {
                        TempData["ErrorPassword"] = "Неверный пароль";
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        var CookieId = new HttpCookie("AuthId")
                        {
                            Value = user1.Id.ToString(),
                            Expires = DateTime.Now.AddHours(3),
                        };
                        HttpContext.Response.Cookies.Add(CookieId);
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult LogOff()
        {
            AuthHelp.LogOffUser(HttpContext);
            return RedirectToAction("Index", "Home");
        }
    }
}

SiteAudi/SiteAudi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SiteAudi.Content;

namespace SiteAudi.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            ModelImage modelimage = new ModelImage();
            modelimage.IMAGES.AddRange(System.IO.Directory.GetFiles(@"D:\Универ\Web-технологии\4 курс\ЛР2\SiteAudi\SiteAudi\Images\SlideShowImages"));
            for (int i = 0; i < modelimage.IMAGES.Count; i++)
            {
                modelimage.IMAGES[i] = modelimage.IMAGES[i].Replace(@"D:\Универ\Web-технологии\4 курс\ЛР2\SiteAudi\SiteAudi", "~");
                modelimage.IMAGES[i] = modelimage.IMAGES[i].Replace(@"\", "/");
            } 
            return View(modelimage);
        }

    }
}

SiteAudi/SiteAudi/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SiteAudi.Models;

namespace SiteAudi.Controllers
{
    public class RegistrationController : Controller
    {
        DataBaseContext dbcontext = new DataBaseContext();
        //
        // GET: /Registration/

        public ActionResult Index()
        {
            return View();
        }
    
        [HttpPost]
        public ActionResult Index(User user)
        {
            if(ModelState.IsValid)
            {
                string email = user.Email;
                User user1 = dbcontext.Users.FirstOrDefault(u => u.Email == email);
                if(user1==null)
                {
                    if (user.Password == Request.Params["ConfirmPassword"])
                    {
                        dbcontext.Users.Add(user);
                        dbcontext.SaveChanges();
                        return View("~/Views/Registration/ResultRegistration.cshtml");
                    }
                    else
                        ModelState.AddModelError("Password", "ПАРОЛИ НЕ СОВПАДАЮТ.");
                }
                else
                    ModelState.AddModelError("Email", "Пользователь с таким Email уже есть.");
            }
            return View();
        }
    }
}

SiteAudi/SiteAudi/Views/Home/Index.cshtml
@model SiteAudi.Content.ModelImage
@using SiteAudi.Content
       
<script src="@Url.Content("~/Scripts/ScriptLR2.js")" type="text/javascript"></script>
<body>
        @section Registration
        {
            @if (HttpContext.Current.Request.Cookies["AuthId"] != null)
            {
                <div class="registration">
                @using (Html.BeginForm("LogOff", "Authentication"))
                {
                    <label>Здравствуйте, <br /> @AuthHelp.GetUserById(int.Parse(HttpContext.Current.Request.Cookies["AuthId"].Value)).FirstName</label> <br />  
                    <input type="submit" value="Выйти" class="button" />
                }
                </div> 
            }
            else
            {
                <div class="registration">
                    @using (Html.BeginForm("Index", "Authentication"))
                    {
                            <label>Вход</label> <br />
                            @Html.TextBox("login", null, new { placeholder="Email", pattert = @"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" })<br />
                            <br />
                            @Html.Password("pwd", null, new { placeholder = "Пароль" })<br />
                            if (TempData["ErrorPassword"] != "")
                            {
                                <text>@TempData["ErrorPassword"]</text>
                            }
                            <input type="submit" name="enter" value="Войти" class="button" />
                            @Html.ActionLink("Регистрация", "Index", "Registration")
                    }
                    </div>
            }       
        }

        @section Slider
        {
            <div class="slide">
                @for (int i = 0; i < Model.IMAGES.Count; i++)
                {
                    <img src="@Url.Content(@Model.IMAGES[i])" id="@i" />
                }
            </div>
        }
        @section News
        {
        <div class="news">
            Новости мира Ауди
                <ul>
                    <li>
                        <figure>
                            <a href="http://audi.infocar.com.ua/news_103047.html"><img src="@Url.Content("~/Images/NewsImages/1.jpg")" /></a>
                                <figcaption>"Дизельный скандал"</figcaption>
                        </figure>
                    </li>
                    <li>
                        <figure>
                            <a href="http://audi.infocar.com.ua/news_103065.html"><img src="@Url.Content("~/Images/NewsImages/2.jpg")" /></a>
                                <figcaption>Audi на Луне</figcaption>
                        </figure>
                    </li>
                    <li>
                        <figure>
                            <a href="http://audi.infocar.com.ua/news_102997.html"><img src="@Url.Content("~/Images/NewsImages/3.jpg")" /></a>
                            <figcaption>Светотехника будущего</figcaption>
                        </figure>
                    </li>
                </ul> 
        </div>
        }
        @section Footer {
            Я хочу знать о специальных предложениях Audi первым
            <input type="text" name="email" placeholder="E-mail" />
            <a href="#">Подписаться</a>
        }
</body>