SiteAudi/SiteAudi/Models/Car.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI.WebControls;

namespace SiteAudi.Models
{
    public class Car
    {
        // ID машины
        public int Id { get; set; }

        // модель
        public string ModelCar { get; set; }

        // описание
        public string DescriptionCar { get; set; }

        // цена
        public int PriceCar { get; set; }

        // путь к картинке
        public string ImagePathCar { get; set; }

        // категория (внешний ключ)
        public int CategoryId { get; set; }

        // навигационное свойство
        public Category Category { get; set; }
    }
}

SiteAudi/SiteAudi/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SiteAudi.Models;
using System.Data.Entity;
using System.Data;
using System.Data.SqlClient;
using System.IO;

namespace SiteAudi.Controllers
{
    public class CarController : Controller
    {
        DataBaseContext dbcontext = new DataBaseContext();
        //
        // GET: /Car/

        public ActionResult Index(bool? Cars, bool? SUV)
        {
            var cars = dbcontext.Cars.Include(category => category.Category);
            if (Cars == SUV == true)
            {
                return View(cars);
            }
            else
            {
                if (Cars == true)
                {
                    cars = cars.Where(c => c.CategoryId == 1);
                    return View(cars); 
                }
                else
                {
                    if (SUV == true)
                    {
                        cars = cars.Where(c => c.CategoryId == 3);
                        return View(cars);
                    }
                    else
                        return View(cars);
                }
            }  
        }
        protected override void Dispose(bool disposing)
        {
            dbcontext.Dispose();
            base.Dispose(disposing);
        }
    }
}

SiteAudi/SiteAudi/Controllers/OrderCarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SiteAudi.Models;

namespace SiteAudi.Controllers
{
    public class OrderCarController : Controller
    {
        DataBaseContext dbContext = new DataBaseContext();
        //
        // GET: /Order/

        [HttpGet]
        public ActionResult Index(int IdOrderCar)
        {
            if (HttpContext.Request.Cookies["AuthId"] != null)
            {
                ViewBag.IdOrderCar = IdOrderCar;
                return View();
            }
            else
            {
                return View("~/Views/OrderCar/AuthenticationForOrderCar.cshtml");
            }
        }

        [HttpPost]
        public ActionResult Index(OrderCar ordercar)
        {
            if(ModelState.IsValid)
            {
                dbContext.OrderCars.Add(ordercar);
                dbContext.SaveChanges();
                return View("~/Views/OrderCar/ResultOrderCar.cshtml");
            }
            ViewBag.IdOrderCar = ordercar.IdCar;
            return View("~/Views/OrderCar/Index.cshtml");
        }
    }
}

SiteAudi/SiteAudi/Views/Car/Index.cshtml
@model IEnumerable<SiteAudi.Models.Car>

<body>
        <div class="filter">
            @using (Html.BeginForm("Index", "Car", FormMethod.Post))
            {
                <label>Фильтр</label> <br /> <br />
                @Html.CheckBox("Cars", false) <text>Легковые</text> <br />
                <br />
                @Html.CheckBox("SUV", false) <text>Внедорожные</text><br />
                <input type="submit" name="apply" value="Применить" class="button" />
            }
        </div>

    <table class="tablecar">
        <tr>
            <td><p>Модель</p></td>
            <td><p>Описание</p></td>
            <td><p>Цена</p></td>
            <td><p>Категория</p></td>
            <td colspan="2"></td>
        </tr>
        @foreach (SiteAudi.Models.Car car in Model)
        {
            <tr>
                <td><p>@Html.DisplayFor(modelItem => car.ModelCar)</p></td>
                <td><p>@Html.DisplayFor(modelItem => car.DescriptionCar)</p></td>
                <td><p>@Html.DisplayFor(modelItem => car.PriceCar)</p></td>
                <td><p>@Html.DisplayFor(modelItem => car.Category.NameCategory)</p></td>
                <td><p><img src="@Url.Content(car.ImagePathCar)" /></p></td>
                <td><p>@Html.ActionLink("Купить", "Index", "OrderCar", new { IdOrderCar=car.Id }, null)</p></td>
            </tr>
        }
    </table>

    @section Footer {
        Я хочу знать о специальных предложениях Audi первым
        <input type="text" name="email" placeholder="E-mail" />
        <a href="#">Подписаться</a>
    }
</body>