SiteAudi/SiteAudi/Controllers/AccessoryController.cs
using SiteAudi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteAudi.Controllers
{
    public class AccessoryController : Controller
    {
        DataBaseContext dbcontext = new DataBaseContext();
        //
        // GET: /Accessory/

        public ActionResult Index()
        {
            return View(dbcontext.Accessories);
        }

    }
}

SiteAudi/SiteAudi/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SiteAudi.Models;
using System.Data.Entity;
using System.Data;
using System.Data.SqlClient;
using System.IO;

namespace SiteAudi.Controllers
{
    public class CarController : Controller
    {
        DataBaseContext dbcontext = new DataBaseContext();
        //
        // GET: /Car/

        public ActionResult Index(bool? Cars, bool? SUV)
        {
            var cars = dbcontext.Cars.Include(category => category.Category);
            if (Cars == SUV == true)
            {
                return View(cars);
            }
            else
            {
                if (Cars == true)
                {
                    cars = cars.Where(c => c.CategoryId == 1);
                    return View(cars); 
                }
                else
                {
                    if (SUV == true)
                    {
                        cars = cars.Where(c => c.CategoryId == 3);
                        return View(cars);
                    }
                    else
                        return View(cars);
                }
            }  
        }
        protected override void Dispose(bool disposing)
        {
            dbcontext.Dispose();
            base.Dispose(disposing);
        }
    }
}

SiteAudi/SiteAudi/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteAudi.Controllers
{
    public class ContactsController : Controller
    {
        //
        // GET: /Contacts/

        public ActionResult Index()
        {
            return View();
        }

    }
}

SiteAudi/SiteAudi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Index</title>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/Style.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-2.1.3.min.js")" type="text/javascript"></script>
</head>
<body>
    <header>
        <div class="logoimgleft">
            <img src="@Url.Content("~/Images/LogoAudi.jpg")" />
        </div>
        <div class="mainmenu">
            <ul>
                <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                <li>@Html.ActionLink("Авто", "Index", "Car")</li>
                <li>@Html.ActionLink("Аксессуары", "Index", "Accessory")</li>
                <li>@Html.ActionLink("Контакты", "Index", "Contacts")</li>
            </ul>
        </div>
        <div class="logoimgright">
            <img src="@Url.Content("~/Images/LogoAudi.jpg")" />
        </div>
    </header>
    <div class="wrapper">
        @RenderBody()
        @RenderSection("Registration", false)
        @RenderSection("Slider", false)
        @RenderSection("News", false)
        <footer>@RenderSection("Footer",false)</footer>
    </div>   
</body>
</html>